### ISSUE TITLE
Dlib Version Issue Causing Docker Compose Fail

### ISSUE THREAD

**Issue by Alexanderyoungblood** [Alexanderyoungblood/face_recognition#1]
* face_recognition version:
* Python version:
* Operating System:

### Description

If you clone this repository and run docker-compose up --build, the image fails to build.

To be more precise, it fails with a Python SyntaxError: invalid syntax while trying to install Pillow from requirements.txt.

I highly suspect that this is happening because the right version of Pillow for this Docker container has not been annotated on the requirements.txt file, so it is pulling the latest version of Pillow, which is incompatible.

This version issue w/ Pillow is likely causing issues importing the dlib library, which is used by the batching process here:

```python
def batch_face_locations(images, number_of_times_to_upsample=1, batch_size=128):
    """
    Returns an 2d array of bounding boxes of human faces in a image using the cnn face detector
    If you are using a GPU, this can give you much faster results since the GPU
    can process batches of images at once. If you aren't using a GPU, you don't need this function.
    :param images: A list of images (each as a numpy array)
    :param number_of_times_to_upsample: How many times to upsample the image looking for faces. Higher numbers find smaller faces.
    :param batch_size: How many images to include in each GPU processing batch.
    :return: A list of tuples of found face locations in css (top, right, bottom, left) order
    """
    def convert_cnn_detections_to_css(detections):
        return [_trim_css_to_bounds(_rect_to_css(face.rect), images[0].shape) for face in detections]

    raw_detections_batched = _raw_face_locations_batched(images, number_of_times_to_upsample, batch_size)

    return list(map(convert_cnn_detections_to_css, raw_detections_batched))
```

Does anyone know the right versions of Pillow and numpy for this Docker container? Maybe pinpointing those versions would solve the problem.

### What I Did
Just followed the documentation. I uncommented the nvidia-related lines on docker-compose.yml and ran docker-compose up --build.

This is my docker-compose.yml.
```
version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/examples
    build:
      context: .
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      dockerfile: Dockerfile.gpu 
    command: python3 -u find_faces_in_picture_cnn.py
    volumes:
      - ./:/face_recognition
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
    runtime: nvidia
```
